### PR TITLE
Fix office table styling

### LINKED ISSUE #995: Fix styling of map table when user location is unknown
screen shot 2018-08-23 at 2 26 44 pm

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #995

### CODE REVIEW

File: components/area_office_table.js [hunk 1]
```diff
@@ -252,3 +266,8 @@ export default connect(
   mapStateToProps,
   mapDispatchToProps
 )(AreaOfficeTable);
+
+// export default connect(
+//   mapStateToProps,
+//   mapDispatchToProps
+// )(withStyles(styles, { withTheme: true })(AreaOfficeTable));
```
Comment (apmcguigan) [inline components/area_office_table.js]: should be able to remove withStyles from here, and remove comment //

**Comment by apmcguigan** [comment]
capture

Address overflows, especially on smaller window size.

Could probably use a tiny bit of right padding on the distance.

**Review by apmcguigan — APPROVED** [review]
LGTM
