### PR TITLE
GE skip button bug

### LINKED ISSUE #1801: Clicking skip from 1st page in GE w/ veteran selected should go to needs
But instead it goes to service type.

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1801 

The issue was that we were getting the next section using the redux state, which may be incorrect for the current question if skip is clicked (since clicking skip should clear the answer for the current question). Also one of our tests was wrong.

### CODE REVIEW

File: __tests__/components/guided_experience_test.js [hunk 1]
```diff
@@ -137,8 +137,6 @@ describe("GuidedExperience", () => {
         .find("#skipLink")
         .first()
         .props().href
-    ).toEqual(
-      "/serviceHealthIssue?lng=en&patronType=veteran&selectedNeeds=1,2"
```
Comment (SupeDeDupe) [inline __tests__/components/guided_experience_test.js:141]: lol what even was this test

**Review by SupeDeDupe — APPROVED** [review]
Awesome! Good call on adding those functions 🦑🥇
