### PR TITLE
Fixed print page bug

### LINKED ISSUE #1527: Print page fonts
The print page first pops up in one font, and then changes font if the user clicks the cancel button on the print popup window. 

screen shot 2018-12-04 at 8 45 50 am
screen shot 2018-12-04 at 8 45 59 am

### PR DESCRIPTION
**Pull request by SupeDeDupe**
Closes #1527

### CODE REVIEW

**Comment by brdunfield** [comment]
This looks like it just loads with the default font, vs Merriweather?

**Comment by SupeDeDupe** [comment]
Yep, that is correct. The main bug was that it dynamically changed fonts at some point between opening the page and closing the print window, if the print page was not opened in a new tab. Now that it always opens in a new tab, the user never sees it changing fonts in that way.

File: components/header_link.js [hunk 1]
```diff
@@ -64,6 +65,7 @@ class HeaderLink extends Component {
               ? cx(style, grey, className)
               : cx(style, className)
           }
+          target={target}
```
Comment (smcmurtry) [inline components/header_link.js]: I think it would be better to leave `target` out of this file - the prop will be passed through automatically with `{...otherProps}`. Try reverting your changes to this component - the behaviour should be the same.

Comment (SupeDeDupe) [reply components/header_link.js]: If I remove changes from this file, I don't see how the print page will open in a new tab...

Comment (smcmurtry) [reply components/header_link.js]: Give it a try and see! Because of line 71, any prop passed into `HeaderLink` gets passed automatically to the `a` element.

Comment (SupeDeDupe) [reply components/header_link.js]: I tried removing line 68 along with other lines I had added, but this causes it to open in the same tab, not a new one.

Comment (smcmurtry) [reply components/header_link.js]: Okay it should be working now - the ... on line 54 was missing

**Review by smcmurtry — APPROVED** [review]
🦑
