### PR TITLE
Another attempt to get 2 GA trackers set up 

### LINKED ISSUE #1678: Get google analytics working for real this time
Although it was working when we set the `GA_UA_CDS` env variable in heroku, it doesn't work when we set both `GA_UA` and `GA_UA_CDS`.

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1678 

For some reason the solution is to add a name to one of the trackers but not the other?! Oh well it seems to work.

### CODE REVIEW

File: utils/analytics.js [hunk 1]
```diff
@@ -1,10 +1,18 @@
...
+    [
+      {
+        trackingId: process.env.GA_UA,
+        gaOptions: { name: "tracker_1" }
+      },
+      {
+        trackingId: process.env.GA_UA_CDS
+      }
+    ]
+    // , { debug: true }
```
Comment (smcmurtry) [inline utils/analytics.js:14]: leaving this in since it will be useful if we ever need to modify this file again

**Review by SupeDeDupe — APPROVED** [review]
Good job 🦑 👍
