### PR TITLE
Fixed footer/feedback margins

### LINKED ISSUE #873: IE11: footer is not sticking to bottom, missing Privacy link
On each page of the app in IE11: 

image

Observe there's a gap between the footer and bottom of the page, padding issues with the Canada logo, and missing the Privacy link.

### LINKED ISSUE #893: Footer margin/padding is wrong
Hopefully fixing this will also fix #873

screen shot 2018-08-14 at 10 05 53 am

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #893
Closes #873

### CODE REVIEW

File: components/layout.js [hunk 1]
```diff
@@ -14,7 +14,7 @@ import FederalBanner from "../components/federal_banner";
 import Noscript from "../components/noscript";
 
 import classnames from "classnames";
-import { withStyles } from "@material-ui/core//styles";
```
Comment (sastels) [inline components/layout.js:17]: good catch!

**Review by sastels — APPROVED** [review]
awesome!
