### PR TITLE
Fixed styling bugs on benefit card

### LINKED ISSUE #1045: Fix some styling bugs on benefit card
screen shot 2018-08-28 at 4 22 05 pm

and:
screen shot 2018-08-28 at 4 25 42 pm

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1045

### CODE REVIEW

**Comment by sastels** [comment]
Still bad for very narrow phones like the iPhone 5s.

image

File: components/benefit_cards.js [hunk 1]
```diff
@@ -32,7 +32,7 @@ const button = css`
   color: white !important;
   text-align: right !important;
   text-transform: none !important;
-  float: right !important;
+  // float: right !important;
```
Comment (sastels) [inline components/benefit_cards.js]: 🔥

**Review by sastels — APPROVED** [review]
minor comment, good work! 🦑
