### PR TITLE
Fix SSR

### LINKED ISSUE #1582: janky beta banner
The upgrade to emotion 10 seems to have had the effect that the SSR of the Beta banner isn't quite the same as the client side rendering 😞 The effect is that on load the banner is initially a few pixels shorter, then pops in at full size. Text in the banner is correct throughout.

### PR DESCRIPTION
**Pull request by sastels**
fixes #1582 

Problem was that gcui is based on emotion 9, this didn't play well with emotion 10 and SSR.

Removed our dependency on gcui by copying `PhaseBadge` and `WordMark` into the VAC codebase (and changing both to emotion 10)

### CODE REVIEW

File: components/phase_badge.js [hunk 1]
```diff
@@ -0,0 +1,26 @@
+import React from "react";
+import PropTypes from "prop-types";
+import styled from "@emotion/styled";
+import { globalTheme } from "../theme";
+// import { mediaQuery } from '../utils'
```
Comment (smcmurtry) [inline components/phase_badge.js]: 🔥

**Review by smcmurtry — APPROVED** [review]
Looks fixed, thank you!! 🦑
