### PR TITLE
Clear future profile questions in the GE

### LINKED ISSUE #1818: Clicking skip should clear future profile questions (but not needs)
To reproduce the bug:
1. Answer veteran for patron type
2. answer the remaining profile questions 
3. on summary page, click to edit patron type
4. skip patron type question
5. you now go to the status question and the state in the url query params makes no sense

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1818

### CODE REVIEW

File: __tests__/components/guided_experience_test.js [hunk 1]
```diff
@@ -139,4 +139,19 @@ describe("GuidedExperience", () => {
         .props().href
     ).toEqual("/needs?lng=en&patronType=veteran&selectedNeeds=1,2");
   });
+
+  it("skip button has the correct href, clears future questions", () => {
```
Comment (SupeDeDupe) [inline __tests__/components/guided_experience_test.js:143]: Nice test 👌

**Review by SupeDeDupe — APPROVED** [review]
Awesome 👍 🦑
