### PR TITLE
Created feedback_submitted pg + fixed feedback pg styling

### LINKED ISSUE #1821: Add feedback page response page
screen shot 2019-02-08 at 10 20 17 am

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c5b2b6a91c96d430b24369d

### PR DESCRIPTION
**Pull request by SupeDeDupe**
Closes #1821 and #1817

### CODE REVIEW

**Comment by SupeDeDupe** [comment]
Need to create tests. Also, I accidentally committed to master, but I think I successfully undid that...

File: components/radio_selector.js [hunk 1]
```diff
@@ -13,6 +13,12 @@ const formControl = css`
 `;
 const formLabel = css`
   margin-bottom: 10px;
+  color: ${globalTheme.colour.greyishBrown};
```
Comment (SupeDeDupe) [inline components/radio_selector.js:16]: The radio button stying wasn't following design so much before...

File: components/text_area.js [hunk 2]
```diff
@@ -12,20 +12,20 @@ const HintText = styled("span")({
 });
 
 const LabelText = styled("span")({
-  fontFamily: globalTheme.fontFamily,
+  fontFamily: `${globalTheme.fontFamily}`,
```
Comment (SupeDeDupe) [inline components/text_area.js]: I think this is the notation?? I must not have noticed the way I was writing it the first time in this file.

File: server.js [hunk 3]
```diff
@@ -124,10 +124,10 @@ Promise.resolve(getAllData()).then(allData => {
             source: "/server.js"
           });
         });
-      } else if (req.url.includes("data-validation") && !staging) {
-        res
-          .status(404)
-          .send("The Data Validation page only exists on the staging app.");
+        // } else if (req.url.includes("data-validation") && !staging) {
```
Comment (SupeDeDupe) [inline server.js]: Commenting this out allows devs to refresh cache on local host to see the airtable changes during development. But this line should never be commented out in the master branch.

**Review by SupeDeDupe — COMMENTED** [review]
Data will need to be pulled from Airtable at the same time this PR is merged so we don't have a "key" showing up everywhere, like here:

https://vac-poc-pr-base-pr-1823.herokuapp.com/feedback_submitted

This is something we'll have to think about when adding content in Airtable for features being developed --> the conflict being that there could be admin users testing things in Airtable + the staging app which aren't ready to be pushed to prod, but the devs have a feature + content ready.

File: server.js (hunk 3 above)
Comment (sastels) [reply server.js]: We could have some sort of "DEV" environment variable flag on our laptops that would cause the data-validation page to be there. Possibly something like the app would use the static `data/data.json` file, but you could go to the data-validation page and click Refresh if you wanted to load from live Airtable.

Comment (SupeDeDupe) [reply server.js]: Yeah, that could work

File: components/text_area.js [hunk 4]
```diff
@@ -18,9 +18,9 @@ const LabelText = styled("span")({
   display: "block",
   clear: "none",
   fontWeight: 400,
-  fontSize: "18px",
+  fontSize: "20px",
```
Comment (smcmurtry) [inline components/text_area.js:21]: in the design this is 24px

Comment (smcmurtry) [reply components/text_area.js:21]: Also the multiple choice question is 24px and the options are 21px

**Review by smcmurtry — APPROVED** [review]
Looks good! Ignore my font size comments. 🦑
