### PR TITLE
Analytics fix

### LINKED ISSUE #1716: Analytics not working for multiple trackers

### PR DESCRIPTION
**Pull request by SupeDeDupe**
Closes #1716
@thomascraig's solution 👏

### CODE REVIEW

**Comment by SupeDeDupe** [comment]
Should note there is a weird thing happening where each tracker attempts the set and send twice:

screen shot 2019-01-17 at 1 03 31 pm

And it shows two query attempts for each tracker:

screen shot 2019-01-17 at 1 01 51 pm

File: utils/analytics.js [hunk 1]
```diff
@@ -5,30 +5,36 @@ export const initGA = () => {
...
   );
-  ReactGA.set({ anonymizeIp: true });
+  ReactGA.set({ anonymizeIp: true }, ["tracker_1"]);
+  ReactGA.set({ anonymizeIp: true }, ["tracker_2"]);
 };
 
 export const logPageView = () => {
-  ReactGA.set({ page: window.location.pathname });
-  ReactGA.pageview(window.location.pathname);
+  ReactGA.set({ page: window.location.pathname }, ["tracker_1"]);
```
Comment (SupeDeDupe) [inline utils/analytics.js:22]:
```
 ga("tracker_1.set", "page", window.location.pathname);
 ga("tracker_1.send", "pageview", window.location.pathname);
 ga("tracker_2.set", "page", window.location.pathname);
 ga("tracker_2.send", "pageview", window.location.pathname);
```
Also works, but fails the tests because ga isn't declared in them.

**Review by smcmurtry — APPROVED** [review]
Looks good! Testing by setting the env variable in heroku seemed to work. Thanks for figuring this out! 🦑
