### PR TITLE
Fixed "define is not defined" bug

### LINKED ISSUE #1937: details_polyfill error
error  'define' is not defined

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1937

### CODE REVIEW

File: utils/details_polyfill.js [hunk 1]
```diff
@@ -1,8 +1,4 @@
-void (function(root, factory) {
-  if (typeof define === "function" && define.amd) define(factory);
-  else if (typeof exports === "object") module.exports = factory();
-  else factory();
-})(this, function() {
```
Comment (smcmurtry) [inline utils/details_polyfill.js:5]: I have no idea what all this factory stuff was doing

**Review by SupeDeDupe — APPROVED** [review]
🙌 🦑
