### PR TITLE
Fixed wrong font size in links in contact section

### LINKED ISSUE #1735: Font-size is wrong for links in contact section
screen shot 2019-01-22 at 4 00 26 pm

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1735

### CODE REVIEW

File: pages/map.js [hunk 1]
```diff
@@ -86,7 +86,10 @@ export class Map extends Component {
               <Body>
                 <p>
                   {t("map.contact_1") + " "}
-                  <AnchorLink fontSize={18} href={"tel:+" + t("contact.phone")}>
+                  <AnchorLink
+                    fontSize="18px"
```
Comment (SupeDeDupe) [inline pages/map.js:90]: I think fontSize needs to be rewritten like this in guided_experience_summary.js. It's currently `fontSize={24}` in 2 places

**Comment by smcmurtry** [comment]
@SupeDeDupe I just merged in master and guided_experience_summary.js is no longer using the `AnchorLink` component.

**Review by SupeDeDupe — APPROVED** [review]
Cool cool 😎 👍
