### PR TITLE
fix contact us button

### LINKED ISSUE #1294: Contact Us button not working in master
Worked before the merge? I R confuzd

### PR DESCRIPTION
**Pull request by sastels**
fixes #1294 

basically, don't use Next for this button. Perhaps revisit in the future.

### CODE REVIEW

File: pages/map.js [hunk 1]
```diff
@@ -152,7 +152,7 @@ Map.propTypes = {
   i18n: PropTypes.object.isRequired,
   t: PropTypes.func.isRequired,
   areaOffices: PropTypes.array.isRequired,
-  referrer: PropTypes.array,
+  referrer: PropTypes.string,
```
Comment (sastels) [inline pages/map.js:153]: this was wrong, and throwing a warning

**Comment by sastels** [comment]
[User has guidance if their filters produce a no results page](https://trello.com/c/XdSmvnK2/16-user-has-guidance-if-their-filters-produce-a-no-results-page)

**Review by smcmurtry — APPROVED** [review]
LGTM 🦑
