### PR TITLE
Skip button bug

### LINKED ISSUE #1517: Skip button functionality
If a radio button is selected when the user clicks the skip button, the answer is still saved as a breadcrumb.

### PR DESCRIPTION
**Pull request by smcmurtry**
Closes #1517 

It's a bit ugly but I think it's working.

### CODE REVIEW

File: components/guided_experience.js [hunk 1]
```diff
@@ -33,16 +35,56 @@ const body = css`
...
+      const dynamicStepNumber = displayable_sections.indexOf(id);
+      let nextSection;
+      if (dynamicStepNumber + 1 >= displayable_sections.length) {
+        nextSection = "summary";
+        if (clearCurrentQuestion && id === "needs") {
+          const newUrl = mutateUrl(url, "/summary", {
+            section: "",
+            selectedNeeds: {}
+          });
+          window.location.href = newUrl;
```
Comment (smcmurtry) [inline components/guided_experience.js:65]: For some reason I couldn't make this work with `Router.push`

**Review by brdunfield — APPROVED** [review]
Nice! Didn't need to make new checkboxes 👍  🦑
