### PR TITLE
Feedback footer implementation

### LINKED ISSUE #1796: Change feedback bar in footer
Add "did something go wrong?" and change current content to "Was this information useful?" Keep the same functionality for > Yes. Should be done in sync with #1800

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5b758b92156c13b1cbd5a0a0
screen shot 2019-02-04 at 1 25 55 pm

### LINKED ISSUE #1799: Add component for > No from feedback footer
Implement the design and write functionality.

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c3e07221e752a0ed5bf97cb

screen shot 2019-02-04 at 1 58 48 pm

### LINKED ISSUE #1800: Add component for clicking "did something go wrong?" from feedback footer
Implement the design and write functionality.

https://app.zeplin.io/project/5acbd659dc553ec84805afd4/screen/5c3e07221e752a0ed5bf97cb

screen shot 2019-02-04 at 2 00 00 pm

### PR DESCRIPTION
**Pull request by SupeDeDupe**
Closes #1796, closes #1800, closes #1799

### CODE REVIEW

**Comment by SupeDeDupe** [comment]
Need to add and revise tests

File: components/feedbackBar.js [hunk 1]
```diff
@@ -92,7 +100,7 @@ export class FeedbackBar extends Component {
     this.setState({ commentSubmitted: true });
     let payload = {
       whatWereYouDoing: this.state.action,
-      whatWentWrong: this.state.failure,
+      howCanInfoBeMoreUseful: this.state.failure,
```
Comment (smcmurtry) [inline components/feedbackBar.js]: I think this should go to the column whatWentWrong in airtable. Maybe if you renamed the state variables (`action` and `failure`) it would be more obvious what's going on.

**Comment by smcmurtry** [comment]
I think there should be a bit more space between the question and the bottom of the bar: 
screen shot 2019-02-12 at 3 36 06 pm

**Comment by SupeDeDupe** [comment]
@smcmurtry I noticed that and it seems to be the Header, but I'm not sure how to eliminate that space without changing the component.

File: __tests__/components/feedback_bar_test.js [hunk 2]
```diff
@@ -53,32 +53,32 @@ describe("Feedback bar", () => {
     });
   });
 
-  it("editing the what were you doing text field updates the action state", () => {
+  it("editing the what were you doing text area updates the bug state", () => {
```
Comment (smcmurtry) [inline __tests__/components/feedback_bar_test.js:56]: I think this is no longer the "what were you doing" text area. Maybe the title could be: "clicking to report a bug and editing the text area updates the bug state"

**Review by smcmurtry — APPROVED** [review]
Great work Sarah! I just have a minor comment on the test name, and can you also merge in master to get the new content to make sure that looks good before merging this? 🦑
